source 'https://rubygems.org'
gem 'knife-linode', git: 'https://github.com/onetwotrip/knife-linode.git'
gem 'chef'
gem 'git', git: 'https://github.com/onetwotrip/ruby-git.git'
gem 'colorize'
gem 'SimpleConfig', git: 'https://github.com/onetwotrip/SimpleConfig'
gem 'berkshelf'
